/* =========================================================================
   SECTION 2 — AGGREGATION & GROUPING (Q16–Q35)
   ========================================================================= */

-- Q16. What is the total premium collected, broken down by region?
SELECT P.REGION, SUM(S.PREMIUM) AS TOTAL_PREMIUM
FROM PNC_PROPERTY P
JOIN PNC_SALES S ON P.PROPERTY_ID = S.PROPERTY_ID
GROUP BY P.REGION
ORDER BY TOTAL_PREMIUM DESC;


-- Q17. What is the average claimed amount per loss cause (fire, flood, theft, etc.)?
SELECT S.COVERAGE_TYPE, ROUND(AVG(C.CLAIMED_AMOUNT), 2) AS AVG_CLAIM_AMOUNT
FROM PNC_SALES S
JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
GROUP BY S.COVERAGE_TYPE
ORDER BY AVG_CLAIM_AMOUNT DESC;


-- Q18. How many policies does each coverage type have, and what's the total coverage amount?
SELECT COVERAGE_TYPE,
       COUNT(*) AS TOTAL_NUMBER_POLICY,
       SUM(COVERAGE_AMOUNT) AS TOTAL_COVERAGE
FROM PNC_SALES
GROUP BY COVERAGE_TYPE
ORDER BY TOTAL_NUMBER_POLICY DESC;


-- Q19. What is the claim frequency (number of claims) per region?
SELECT P.REGION, COUNT(C.CLAIM_ID) AS NUMBER_OF_CLAIM
FROM PNC_PROPERTY P
JOIN PNC_SALES S ON P.PROPERTY_ID = S.PROPERTY_ID
JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
GROUP BY P.REGION
ORDER BY NUMBER_OF_CLAIM DESC;


-- Q20. Which industry generates the highest total annual revenue among our clients?
SELECT INDUSTRY, SUM(ANNUAL_REVENUE) AS TOTAL_ANNUAL_REVENUE
FROM PNC_CUSTOMER
GROUP BY INDUSTRY
ORDER BY TOTAL_ANNUAL_REVENUE DESC;

-- Bonus: rank clients within each industry by revenue.
SELECT INDUSTRY, NAME, SUM(ANNUAL_REVENUE) AS REVENUE,
       ROW_NUMBER() OVER (PARTITION BY INDUSTRY ORDER BY SUM(ANNUAL_REVENUE) DESC) AS INDUSTRY_RANK
FROM PNC_CUSTOMER
GROUP BY INDUSTRY, NAME;


-- Q21. What's the average property value by construction type?
SELECT CONSTRUCTION_TYPE, ROUND(AVG(PROPERTY_VALUE), 2) AS AVG_PROPERTY_VALUE
FROM PNC_PROPERTY
GROUP BY CONSTRUCTION_TYPE
ORDER BY AVG_PROPERTY_VALUE DESC;


-- Q22. How many claims fall into each claim status, and what percentage of total claims does each represent?
SELECT CLAIM_STATUS,
       COUNT(*) AS CLAIM_COUNT,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PNC_CLAIMS), 2) AS PCT_OF_TOTAL
FROM PNC_CLAIMS
GROUP BY CLAIM_STATUS
ORDER BY CLAIM_COUNT DESC;


-- Q23. What is the total approved claim amount per agent (agent-level loss exposure)?
SELECT A.AGENT_ID, A.AGENT_NAME, SUM(C.APPROVED_AMOUNT) AS TOTAL_APPROVED_CLAIM
FROM PNC_AGENT A
JOIN PNC_SALES S ON A.AGENT_ID = S.AGENT_ID
JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
GROUP BY A.AGENT_ID, A.AGENT_NAME
ORDER BY TOTAL_APPROVED_CLAIM DESC;


-- Q24. Find the number of properties per disaster risk zone, and the average property value in each zone.
SELECT DISASTER_RISK_ZONE,
       COUNT(*) AS NUMBER_OF_PROPERTIES,
       ROUND(AVG(PROPERTY_VALUE), 2) AS AVG_PROPERTY_VALUE
FROM PNC_PROPERTY
GROUP BY DISASTER_RISK_ZONE
ORDER BY NUMBER_OF_PROPERTIES DESC;


-- Q25. What is the overall book-wide loss ratio (total approved claims / total premium)?
WITH CLAIMS_BY_POLICY AS (
    SELECT POLICY_ID, SUM(APPROVED_AMOUNT) AS APPROVED_CLAIM
    FROM PNC_CLAIMS
    GROUP BY POLICY_ID
)
SELECT ROUND(SUM(COALESCE(C.APPROVED_CLAIM, 0)) * 100.0 / NULLIF(SUM(S.PREMIUM), 0), 2) AS OVERALL_LOSS_RATIO
FROM PNC_SALES S
LEFT JOIN CLAIMS_BY_POLICY C ON S.POLICY_ID = C.POLICY_ID;


-- Q26. Break the loss ratio down by coverage type — which coverage type is the least profitable?
WITH CLAIMS_BY_POLICY AS (
    SELECT POLICY_ID, SUM(APPROVED_AMOUNT) AS APPROVED_CLAIM
    FROM PNC_CLAIMS
    GROUP BY POLICY_ID
)
SELECT S.COVERAGE_TYPE,
       ROUND(SUM(COALESCE(C.APPROVED_CLAIM, 0)) * 100.0 / NULLIF(SUM(S.PREMIUM), 0), 2) AS LOSS_RATIO
FROM PNC_SALES S
LEFT JOIN CLAIMS_BY_POLICY C ON S.POLICY_ID = C.POLICY_ID
GROUP BY S.COVERAGE_TYPE
ORDER BY LOSS_RATIO DESC;


-- Q27. How many distinct clients does each agent serve?
SELECT A.AGENT_ID, A.AGENT_NAME, COUNT(DISTINCT C.CLIENT_ID) AS UNIQUE_CUSTOMER_COUNT
FROM PNC_CUSTOMER C
JOIN PNC_SALES S ON C.CLIENT_ID = S.CLIENT_ID
JOIN PNC_AGENT A ON S.AGENT_ID = A.AGENT_ID
GROUP BY A.AGENT_ID, A.AGENT_NAME
ORDER BY UNIQUE_CUSTOMER_COUNT DESC;


-- Q28. What's the minimum, maximum, and average premium for each region?
SELECT C.REGION,
       MIN(S.PREMIUM) AS MINIMUM_PREMIUM,
       MAX(S.PREMIUM) AS MAXIMUM_PREMIUM,
       ROUND(AVG(S.PREMIUM), 2) AS AVERAGE_PREMIUM
FROM PNC_CUSTOMER C
JOIN PNC_SALES S ON C.CLIENT_ID = S.CLIENT_ID
GROUP BY C.REGION;


-- Q29. Which property type has the highest average claim severity (approved amount per claim)?
SELECT P.PROPERTY_TYPE, ROUND(AVG(C.APPROVED_AMOUNT), 2) AS AVERAGE_CLAIM_AMOUNT
FROM PNC_PROPERTY P
JOIN PNC_SALES S ON P.PROPERTY_ID = S.PROPERTY_ID
JOIN PNC_CLAIMS C ON C.POLICY_ID = S.POLICY_ID
GROUP BY P.PROPERTY_TYPE
ORDER BY AVERAGE_CLAIM_AMOUNT DESC;


-- Q30. Count how many policies were issued each year, to see growth over time.
SELECT EXTRACT(YEAR FROM ISSUE_DATE) AS YEARS, COUNT(*) AS COUNT_OF_POLICY
FROM PNC_SALES
GROUP BY EXTRACT(YEAR FROM ISSUE_DATE)
ORDER BY YEARS ASC;


-- Q31. What percentage of claims are fraud-flagged, broken down by loss cause?
SELECT LOSS_CAUSE,
       COUNT(*) FILTER (WHERE FRAUD_FLAG = 1) AS FRAUD_CLAIM_COUNT,
       COUNT(*) AS TOTAL_CLAIMS,
       ROUND(COUNT(*) FILTER (WHERE FRAUD_FLAG = 1) * 100.0 / COUNT(*), 2) AS FRAUD_PERCENTAGE
FROM PNC_CLAIMS
GROUP BY LOSS_CAUSE
ORDER BY FRAUD_PERCENTAGE DESC;


-- Q32. Find regions where total claimed amount exceeds total premium (HAVING clause use case — potentially unprofitable regions).
SELECT CUS.REGION,
       SUM(C.APPROVED_AMOUNT) AS CLAIMED_AMOUNT,
       SUM(S.PREMIUM) AS TOTAL_PREMIUM,
       (SUM(C.APPROVED_AMOUNT) - SUM(S.PREMIUM)) AS EXCEEDS_AMOUNT
FROM PNC_CUSTOMER CUS
JOIN PNC_SALES S ON CUS.CLIENT_ID = S.CLIENT_ID
LEFT JOIN PNC_CLAIMS C ON C.POLICY_ID = S.POLICY_ID
GROUP BY CUS.REGION
HAVING SUM(C.APPROVED_AMOUNT) > SUM(S.PREMIUM);


-- Q33. What's the average risk adjustment factor per disaster risk zone?
SELECT P.DISASTER_RISK_ZONE, ROUND(AVG(S.RISK_ADJUSTMENT_FACTOR), 2) AS AVG_RISK_FACTOR
FROM PNC_PROPERTY P
JOIN PNC_SALES S ON P.PROPERTY_ID = S.PROPERTY_ID
GROUP BY P.DISASTER_RISK_ZONE
ORDER BY AVG_RISK_FACTOR DESC;


-- Q34. Which agent type (Direct Corporate, Broker, Bancassurance, etc.) writes the highest average premium per policy?
SELECT A.AGENT_TYPE, ROUND(AVG(S.PREMIUM), 2) AS AVG_PREMIUM
FROM PNC_AGENT A
JOIN PNC_SALES S ON A.AGENT_ID = S.AGENT_ID
GROUP BY A.AGENT_TYPE
ORDER BY AVG_PREMIUM DESC;


-- Q35. Find the total number of claims and total approved amount per year, to track loss trends over time.
SELECT EXTRACT(YEAR FROM CLAIM_DATE) AS YEARS,
       COUNT(*) AS TOTAL_NUMBER_OF_CLAIMS,
       SUM(APPROVED_AMOUNT) AS TOTAL_APPROVED_CLAIM
FROM PNC_CLAIMS
GROUP BY EXTRACT(YEAR FROM CLAIM_DATE)
ORDER BY TOTAL_APPROVED_CLAIM ASC;
