/* =========================================================================
   SECTION 5 — COMMON TABLE EXPRESSIONS / CTEs (Q76–Q90)
   ========================================================================= */

-- Q76. Build a client-level summary (premium, claims, loss ratio) using a CTE,
--      then filter for clients with a loss ratio above 80%.
WITH SUMMARY AS (
    SELECT CL.CLIENT_ID, CL.NAME,
           SUM(S.PREMIUM) AS TOTAL_PREMIUM,
           SUM(C.APPROVED_AMOUNT) AS TOTAL_CLAIM,
           ROUND((SUM(C.APPROVED_AMOUNT) * 100.0 / SUM(S.PREMIUM)), 2) AS LOSS_RATIO
    FROM PNC_CUSTOMER CL
    LEFT JOIN PNC_SALES S ON CL.CLIENT_ID = S.CLIENT_ID
    LEFT JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
    GROUP BY CL.CLIENT_ID, CL.NAME
)
SELECT * FROM SUMMARY
WHERE LOSS_RATIO > 80;


-- Q77. Use a CTE to isolate high-value properties (top 10% by value), then find how many of them have filed claims.
WITH HIGH_VALUE_PROPERTIES AS (
    SELECT PROPERTY_ID, PROPERTY_VALUE,
           PERCENT_RANK() OVER (ORDER BY PROPERTY_VALUE DESC) AS PCT_RANK
    FROM PNC_PROPERTY
)
SELECT HV.PROPERTY_ID, HV.PROPERTY_VALUE, COUNT(C.CLAIM_ID) AS TOTAL_CLAIMS
FROM HIGH_VALUE_PROPERTIES HV
JOIN PNC_SALES S ON HV.PROPERTY_ID = S.PROPERTY_ID
LEFT JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
WHERE HV.PCT_RANK <= 0.10
GROUP BY HV.PROPERTY_ID, HV.PROPERTY_VALUE
ORDER BY HV.PROPERTY_VALUE DESC;


-- Q78. Use multiple chained CTEs to compute agent-level loss ratio, then rank agents into performance tiers.
WITH AGENT_PERFORMANCE AS (
    SELECT A.AGENT_ID, A.AGENT_NAME,
           SUM(S.PREMIUM) AS TOTAL_PREMIUM,
           SUM(C.APPROVED_AMOUNT) AS TOTAL_CLAIM
    FROM PNC_AGENT A
    JOIN PNC_SALES S ON A.AGENT_ID = S.AGENT_ID
    LEFT JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
    GROUP BY A.AGENT_ID, A.AGENT_NAME
),
AGENT_LOSS_RATIO AS (
    SELECT A.AGENT_ID, A.AGENT_NAME,
           ROUND((SUM(C.APPROVED_AMOUNT) * 100.0 / SUM(S.PREMIUM)), 2) AS LOSS_RATIO
    FROM PNC_AGENT A
    JOIN PNC_SALES S ON A.AGENT_ID = S.AGENT_ID
    LEFT JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
    GROUP BY A.AGENT_ID, A.AGENT_NAME
)
SELECT A1.AGENT_ID, A1.AGENT_NAME, A1.TOTAL_PREMIUM, A1.TOTAL_CLAIM, A2.LOSS_RATIO,
       CASE
           WHEN A2.LOSS_RATIO >= 100 THEN 'POOR PERFORMANCE'
           WHEN A2.LOSS_RATIO >= 50 AND A2.LOSS_RATIO < 100 THEN 'AVERAGE PERFORMANCE'
           ELSE 'TOP PERFORMANCE'
       END AS PERFORMANCE_TIER
FROM AGENT_PERFORMANCE A1
JOIN AGENT_LOSS_RATIO A2 ON A1.AGENT_ID = A2.AGENT_ID;


-- Q79. Use a recursive CTE to generate a full calendar of months between the earliest and latest
--      policy issue date (useful for a "no gaps" trend report).
WITH RECURSIVE CALENDAR AS (
    SELECT DATE_TRUNC('month', MIN(ISSUE_DATE)) AS MONTH_START,
           DATE_TRUNC('month', MAX(ISSUE_DATE)) AS MAX_MONTH
    FROM PNC_SALES
    UNION ALL
    SELECT MONTH_START + INTERVAL '1 month', MAX_MONTH
    FROM CALENDAR
    WHERE MONTH_START + INTERVAL '1 month' <= MAX_MONTH
)
SELECT MONTH_START FROM CALENDAR ORDER BY MONTH_START;


-- Q80. Use a CTE to find each client's largest single claim, then join back to show client details.
WITH LARGEST_CLAIM AS (
    SELECT S.CLIENT_ID, MAX(C.APPROVED_AMOUNT) AS LARGEST_SINGLE
    FROM PNC_SALES S
    JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
    GROUP BY S.CLIENT_ID
)
SELECT CL.CLIENT_ID, CL.NAME, LC.LARGEST_SINGLE
FROM LARGEST_CLAIM LC
JOIN PNC_CUSTOMER CL ON LC.CLIENT_ID = CL.CLIENT_ID
ORDER BY LC.LARGEST_SINGLE DESC;


-- Q81. Use a CTE to calculate month-over-month premium growth.
WITH MONTH_OVER_MONTH AS (
    SELECT EXTRACT(MONTH FROM ISSUE_DATE) AS MONTH, SUM(PREMIUM) AS TOTAL_PREMIUM
    FROM PNC_SALES
    GROUP BY EXTRACT(MONTH FROM ISSUE_DATE)
)
SELECT MONTH, TOTAL_PREMIUM,
       TOTAL_PREMIUM - LAG(TOTAL_PREMIUM) OVER (ORDER BY MONTH) AS MOM_CHANGE,
       ROUND(
           (TOTAL_PREMIUM - LAG(TOTAL_PREMIUM) OVER (ORDER BY MONTH))
           / LAG(TOTAL_PREMIUM) OVER (ORDER BY MONTH) * 100, 2
       ) AS MOM_PERCENT
FROM MONTH_OVER_MONTH
ORDER BY MONTH;


-- Q82. Use a CTE to flag clients as "high risk" (multiple properties in High disaster zones)
--      then count policies for those clients.
WITH HIGH_RISK_CLIENTS AS (
    SELECT CLIENT_ID, COUNT(*) AS HIGH_RISK_PROPERTY_COUNT
    FROM PNC_PROPERTY
    WHERE DISASTER_RISK_ZONE LIKE 'High%'
    GROUP BY CLIENT_ID
    HAVING COUNT(*) > 1
)
SELECT H.CLIENT_ID, H.HIGH_RISK_PROPERTY_COUNT, COUNT(S.POLICY_ID) AS POLICY_COUNT
FROM HIGH_RISK_CLIENTS H
JOIN PNC_SALES S ON H.CLIENT_ID = S.CLIENT_ID
GROUP BY H.CLIENT_ID, H.HIGH_RISK_PROPERTY_COUNT
ORDER BY H.HIGH_RISK_PROPERTY_COUNT DESC;


-- Q83. Use a CTE to compute each coverage type's share of total premium (a portfolio mix report).
WITH COVERAGE_TOTALS AS (
    SELECT COVERAGE_TYPE, SUM(PREMIUM) AS COVERAGE_PREMIUM
    FROM PNC_SALES
    GROUP BY COVERAGE_TYPE
)
SELECT COVERAGE_TYPE, COVERAGE_PREMIUM,
       ROUND(COVERAGE_PREMIUM * 100.0 / SUM(COVERAGE_PREMIUM) OVER (), 2) AS PCT_OF_TOTAL_PREMIUM
FROM COVERAGE_TOTALS
ORDER BY PCT_OF_TOTAL_PREMIUM DESC;


-- Q84. Use a CTE to identify claims filed within 30 days of policy issuance
--      (a red flag for possible pre-existing-condition fraud).
WITH CLAIM_TIMING AS (
    SELECT C.CLAIM_ID, C.POLICY_ID, C.CLAIMED_AMOUNT, C.APPROVED_AMOUNT,
           S.ISSUE_DATE, C.CLAIM_DATE,
           (C.CLAIM_DATE - S.ISSUE_DATE) AS DAYS_TO_CLAIM
    FROM PNC_CLAIMS C
    JOIN PNC_SALES S ON S.POLICY_ID = C.POLICY_ID
)
SELECT CLAIM_ID, POLICY_ID, CLAIMED_AMOUNT, APPROVED_AMOUNT, ISSUE_DATE, CLAIM_DATE, DAYS_TO_CLAIM
FROM CLAIM_TIMING
WHERE DAYS_TO_CLAIM > 0 AND DAYS_TO_CLAIM <= 30
  AND APPROVED_AMOUNT <> 0
ORDER BY DAYS_TO_CLAIM ASC;


-- Q85. Use two CTEs to compare average premium for clients WITH claims vs. clients WITHOUT claims.
WITH CLIENT_WITH_CLAIM AS (
    SELECT CL.CLIENT_ID, CL.NAME, ROUND(AVG(S.PREMIUM), 2) AS AVG_PREMIUM_WITH_CLAIM
    FROM PNC_CUSTOMER CL
    JOIN PNC_SALES S ON CL.CLIENT_ID = S.CLIENT_ID
    JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
    GROUP BY CL.CLIENT_ID, CL.NAME
),
CLIENT_WITHOUT_CLAIM AS (
    SELECT CL.CLIENT_ID, CL.NAME, ROUND(AVG(S.PREMIUM), 2) AS AVG_PREMIUM_WITHOUT_CLAIM
    FROM PNC_CUSTOMER CL
    JOIN PNC_SALES S ON CL.CLIENT_ID = S.CLIENT_ID
    LEFT JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
    WHERE C.CLAIM_ID IS NULL
    GROUP BY CL.CLIENT_ID, CL.NAME
)
SELECT COALESCE(C1.CLIENT_ID, C2.CLIENT_ID) AS CLIENT_ID,
       COALESCE(C1.NAME, C2.NAME) AS NAME,
       C1.AVG_PREMIUM_WITH_CLAIM,
       C2.AVG_PREMIUM_WITHOUT_CLAIM
FROM CLIENT_WITH_CLAIM C1
FULL OUTER JOIN CLIENT_WITHOUT_CLAIM C2 ON C1.CLIENT_ID = C2.CLIENT_ID;


-- Q86. Use a CTE to build a rolling 3-claim moving average of approved amount per policy
--      (for policies with repeat claims).
WITH ORDERED_CLAIMS AS (
    SELECT POLICY_ID, CLAIM_ID, APPROVED_AMOUNT, CLAIM_DATE,
           ROW_NUMBER() OVER (PARTITION BY POLICY_ID ORDER BY CLAIM_DATE) AS RN
    FROM PNC_CLAIMS
),
MOVING_AVG AS (
    SELECT C1.POLICY_ID, C1.CLAIM_ID, C1.CLAIM_DATE,
           ROUND(AVG(C2.APPROVED_AMOUNT), 2) AS ROLLING_3_CLAIM_AVG
    FROM ORDERED_CLAIMS C1
    JOIN ORDERED_CLAIMS C2
      ON C1.POLICY_ID = C2.POLICY_ID
     AND C2.RN BETWEEN C1.RN AND C1.RN + 2
    GROUP BY C1.POLICY_ID, C1.CLAIM_ID, C1.CLAIM_DATE
)
SELECT *
FROM MOVING_AVG
WHERE POLICY_ID IN (
    SELECT POLICY_ID FROM PNC_CLAIMS GROUP BY POLICY_ID HAVING COUNT(*) > 1
)
ORDER BY POLICY_ID, CLAIM_DATE;


-- Q87. Use a CTE to rank clients within their own industry by total premium paid.
WITH CUST_WITH_TP AS (
    SELECT C.CLIENT_ID, C.NAME, C.INDUSTRY, SUM(S.PREMIUM) AS TOTAL_PREMIUM
    FROM PNC_CUSTOMER C
    JOIN PNC_SALES S ON C.CLIENT_ID = S.CLIENT_ID
    GROUP BY C.CLIENT_ID, C.NAME, C.INDUSTRY
)
SELECT CLIENT_ID, NAME, INDUSTRY, TOTAL_PREMIUM,
       ROW_NUMBER() OVER (PARTITION BY INDUSTRY ORDER BY TOTAL_PREMIUM DESC) AS INDUSTRY_RANK
FROM CUST_WITH_TP;


-- Q88. Use a CTE to find the gap between claimed and approved amounts, then flag claims with
--      a haircut greater than 50% (aggressive adjustment).
WITH CLAIM_GAP AS (
    SELECT CLAIM_ID, POLICY_ID, CLAIMED_AMOUNT, APPROVED_AMOUNT,
           (CLAIMED_AMOUNT - APPROVED_AMOUNT) AS GAP,
           CASE
               WHEN CLAIMED_AMOUNT > 0
                AND (CLAIMED_AMOUNT - APPROVED_AMOUNT) * 100 / CLAIMED_AMOUNT > 50
               THEN 'Aggressive Adjustment'
               ELSE 'Normal Adjustment'
           END AS HAIRCUT_FLAG
    FROM PNC_CLAIMS
)
SELECT *
FROM CLAIM_GAP
ORDER BY POLICY_ID, CLAIM_ID;


-- Q89. Use a CTE to compute year-over-year loss ratio and flag years where it worsened vs. the prior year.
WITH YEARLY_LOSS AS (
    SELECT EXTRACT(YEAR FROM S.ISSUE_DATE) AS YEARS,
           ROUND(SUM(C.APPROVED_AMOUNT) * 100.0 / SUM(S.PREMIUM), 2) AS LOSS_RATIO
    FROM PNC_SALES S
    LEFT JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
    GROUP BY EXTRACT(YEAR FROM S.ISSUE_DATE)
)
SELECT YEARS, LOSS_RATIO,
       LAG(LOSS_RATIO) OVER (ORDER BY YEARS) AS PRIOR_YEAR_RATIO,
       CASE
           WHEN LOSS_RATIO > LAG(LOSS_RATIO) OVER (ORDER BY YEARS) THEN 'Worsened'
           ELSE 'Improved/Stable'
       END AS FLAG
FROM YEARLY_LOSS
ORDER BY YEARS;


-- Q90. Use a CTE to segment clients into revenue quartiles, then show claim frequency per quartile.
WITH CLIENT_QUARTILES AS (
    SELECT C.CLIENT_ID, C.COMPANY_NAME, C.ANNUAL_REVENUE,
           NTILE(4) OVER (ORDER BY C.ANNUAL_REVENUE) AS REVENUE_QUARTILE
    FROM PNC_CUSTOMER C
),
CLAIM_FREQUENCY AS (
    SELECT CQ.REVENUE_QUARTILE, COUNT(C.CLAIM_ID) AS CLAIM_FREQUENCY
    FROM CLIENT_QUARTILES CQ
    JOIN PNC_SALES S ON CQ.CLIENT_ID = S.CLIENT_ID
    JOIN PNC_CLAIMS C ON S.POLICY_ID = C.POLICY_ID
    GROUP BY CQ.REVENUE_QUARTILE
)
SELECT 'Q' || REVENUE_QUARTILE AS REVENUE_QUARTILE, CLAIM_FREQUENCY
FROM CLAIM_FREQUENCY
ORDER BY REVENUE_QUARTILE;
